### ISSUE TITLE
move StatisticalTraits.jl to JuliaAI organization

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaAI/StatisticalTraits.jl#14]
Tests on several down stream MLJ related packages are failing for julia 1.0 because julia expected that this package ought to have been moved to JuliaAI organization as shown [here](https://github.com/JuliaRegistries/General/blob/master/S/StatisticalTraits/Package.toml).

I expected that while testing these downstream packages there would be an error installing **StatisticalTraits.jl** with Julia v1.6; but to my surprise, no such error occurs. See [here](https://github.com/JuliaAI/MLJBase.jl/pull/585/checks?check_run_id=2921768414)
@DilumAluthge Could there any reason why this is so?

@ablaom Is there any reason why **StatisticalTraits.jl** hasn't been moved.

**Comment by DilumAluthge** [comment]
Julia 1.6 uses the Pkg server, which can serve packages even if something happens to the underlying repo.

**Comment by ablaom** [comment]
@OkonSamuel Thanks for flagging and thanks @DilumAluthge for clarification.

@vollmersj Can you please transfer ownership of StatisticalTraits.jl to JuliaAI as soon as possible, to reflect the new General.jl designation?

**Comment by DilumAluthge** [comment]
Can this be closed now? Looks like the move is complete.
